export default function SyntheticDataPage() {
  return (
    <article>
      <p className="font-mono text-xs uppercase tracking-wide text-ink-400">
        Synthetic data disclosure
      </p>
      <h1 className="mt-3 font-serif text-3xl">Where this data comes from</h1>

      <p className="mt-6 text-sm leading-relaxed text-ink-700">
        Every customer, login, feature-use event, purchase, refund, support ticket, and sentiment
        record visible in this application is synthetically generated by a seeded simulation
        (<code className="font-mono text-xs">ml/src/synthetic/generate.py</code> in the project
        source). No real company, person, or customer relationship is represented.
      </p>

      <h2 className="mt-8 font-serif text-xl">How it&apos;s generated</h2>
      <p className="mt-3 text-sm leading-relaxed text-ink-700">
        Each synthetic customer is simulated day by day over an 8-month window. A hidden,
        continuous &quot;engagement&quot; trajectory (declining, stable, or growing) drives the
        probability of observable events like logins and support tickets each day. A separate,
        stochastic daily churn hazard - influenced by recent usage decline, sentiment, and
        unresolved support issues, plus randomness - determines whether and when each customer
        churns. Churn is never a deterministic function of any single field.
      </p>

      <h2 className="mt-8 font-serif text-xl">Why simulate instead of using only real datasets</h2>
      <p className="mt-3 text-sm leading-relaxed text-ink-700">
        Public churn datasets (e.g. IBM Telco) provide account-level structure but not the
        behavioral, support, and sentiment history PULSE is built to analyze. The synthetic
        generator produces that missing behavioral layer with realistic, noisy, non-deterministic
        patterns, with a fixed random seed so the same configuration always reproduces the same
        dataset.
      </p>

      <h2 className="mt-8 font-serif text-xl">Reproducing it yourself</h2>
      <p className="mt-3 text-sm leading-relaxed text-ink-700">
        The full generation, training, and evaluation pipeline is documented and runnable from
        the project source - see <code className="font-mono text-xs">ml/README.md</code>.
      </p>
    </article>
  );
}
